version: '3'

services:
  blog-db:
    image: blog-db
    ports: 
      - "5432:5432"
    networks:
      - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "henrique-90@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres123++"
    ports:
      - "15432:80"
    links:
      - blog-db
    depends_on:
      - blog-db
    networks:
      - postgres-network

  blog-api:
    image: blog-api
    ports:
      - "5000:5000"
    depends_on:
      - blog-db
    networks:
      - postgres-network
    stdin_open: true
    tty: true

networks:
  postgres-network:
    driver: bridge